spring:
  profiles:
    include: key
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        type:
          description:
            sql: trace
